providers = ["node", "python"]

[phases.setup]
nixPkgs = [
    "poppler_utils",
    "ghostscript", 
    "cairo",
    "pango",
    "gdk-pixbuf",
    "libffi",
    "mesa",
    "fontconfig",
    "freetype",
    "libjpeg",
    "libpng",
    "zlib",
    "libxml2",
    "libxslt"
]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "npm ci",
    "pip install -r requirements.txt"
]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]

[start]
cmd = "npm run start:railway"