
[phases.setup]
nixPkgs = [
  "nodejs_20", 
  "python311", 
  "python311Packages.setuptools",
  "python311Packages.flask", 
  "python311Packages.flask-cors",
  "python311Packages.flask-sqlalchemy",
  "python311Packages.werkzeug",
  "python311Packages.gunicorn",
  "python311Packages.psycopg2",
  "python311Packages.python-docx",
  "python311Packages.email-validator",
  "python311Packages.wheel",
  "python311Packages.fonttools",
  "python311Packages.numpy",
  "python311Packages.opencv4",
  "python311Packages.fire",
  "python311Packages.lxml",
  "python311Packages.pymupdf"
]
nixLibs = ["stdenv.cc.cc.lib"]

[phases.install]
cmds = [
  "npm install --legacy-peer-deps"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start:railway"
