
[phases.setup]
nixPkgs = [
  "nodejs_20", 
  "python311Full",
  "python311Packages.flask", 
  "python311Packages.flask-cors",
  "python311Packages.flask-sqlalchemy",
  "python311Packages.werkzeug",
  "python311Packages.gunicorn",
  "python311Packages.psycopg2",
  "python311Packages.python-docx",
  "python311Packages.email-validator"
]

[phases.install]
cmds = [
  "npm install --legacy-peer-deps",
  "curl -sSL https://install.python-poetry.org | python3 -",
  "python3 -m ensurepip --upgrade",
  "python3 -m pip install --user pdf2docx"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start:railway"
