[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.2",
    "flask-cors>=6.0.1",
    "gunicorn>=23.0.0",
    "numpy>=2.3.2",
    "opencv-python>=4.11.0.86",
    "pdf2docx>=0.5.8",
    "pdf2image>=1.17.0",
    "pillow>=11.3.0",
    "poppler-utils>=0.1.0",
    "pymupdf>=1.26.4",
    "pytesseract>=0.3.13",
    "python-docx>=1.2.0",
    "requests>=2.32.5",
    "werkzeug>=3.1.3",
]
